### ISSUE TITLE
Error due to the progress bar

### ISSUE THREAD

**Issue by MirzaCengic** [bblonder/hypervolume#4]
Hi Benjamin, 

I am trying to see how the package works, and it looks really interesting, thanks for the effort!
I noticed that an error pops up when you try to run one of the code examples from the documentation.

I am trying to calculate overlap between 2 hypervolumes, and if I try to run the example from `hypervolume_overlap_statistics()`, I an error.

```
library(hypervolume)
data(iris)
hv1 = hypervolume_gaussian(subset(iris, Species=="virginica")[,1:3])
hv2 = hypervolume_gaussian(subset(iris, Species=="versicolor")[,1:3])
hv_set <- hypervolume_set(hv1, hv2, check.memory=FALSE)

hypervolume_overlap_statistics(hv_set)
```

When the `hypervolume_gaussian()` function is run, this is the error message that shows:
`Error in if (!pb$finished == TRUE) { : argument is of length zero`

I checked the source code, and this is due to the progress bar, and if you put `verbose = FALSE`, the code will run, but still this should be checked. Below you can find output of my `sessionInfo()`.

Cheers,
Mirza

> R version 3.4.4 (2018-03-15)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Ubuntu 16.04.4 LTS
> 
> Matrix products: default
> BLAS: /usr/lib/libblas/libblas.so.3.6.0
> LAPACK: /usr/lib/lapack/liblapack.so.3.6.0
> 
> locale:
>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=de_DE.UTF-8        LC_COLLATE=en_US.UTF-8    
>  [5] LC_MONETARY=de_DE.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=de_DE.UTF-8       LC_NAME=C                 
>  [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] hypervolume_2.0.11 rgl_0.95.1441      Rcpp_0.12.19      
> 
> loaded via a namespace (and not attached):
>  [1] raster_2.6-7       magrittr_1.5       maps_3.3.0         progress_1.1.2     magic_1.5-8        MASS_7.3-49       
>  [7] mclust_5.4.1       lattice_0.20-35    R6_2.2.2           geometry_0.3-6     fastcluster_1.1.25 tools_3.4.4       
> [13] grid_3.4.4         data.table_1.11.2  KernSmooth_2.23-15 e1071_1.6-8        rgeos_0.3-28       class_7.3-14      
> [19] abind_1.4-3        yaml_2.1.19        assertthat_0.2.0   Matrix_1.2-14      ks_1.11.3          pdist_1.2         
> [25] sp_1.3-1           compiler_3.4.4     prettyunits_1.0.2  mvtnorm_1.0-8

**Comment by bblonder** [comment]
Hi Mirza,

Unfortunately the author of the progress package made some changes between
version 1.1 and version 1.2 of his package. Try updating progress to 1.2.0
and let me know if this fixes it. If it does, I will update my package to
require version 1.2 and above of this code.

Best wishes,
Ben

**Comment by MirzaCengic** [comment]
Hi Ben,

updating the progress package to v1.2 solved the issue.

Thanks for the response,
Mirza.
